spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy_ong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true